services:
  
  casoft-store-web:
     image: casoftlabs/casoft-store-web:v1.1.3
     container_name: casoft-store-web
     ports:
      - "4200:80"
     environment:
        - API_URL_BACKEND=http://localhost:5214
        - API_URL_PROTOCOL=http
        - API_URL=http://localhost:5214/casoft/
        - IMAGES_URL=http://localhost:5214/
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf   
     depends_on:
      - casoft-store-api-gateway

  casoft-store-api-gateway:
    image: casoftlabs/casoft-store-api-gateway:${TAG}
    container_name: casoft-store-api-gateway
    build:
        context: ../src
        dockerfile: ./Api.Gateway/Dockerfile
    environment:
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_REALM_URL}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - ENDPOINTURI__AUTHAPI=${AUTH_URI_ENDPOINT}
      - FRONTENDURI__URI=${FRONT_END_URI}
      - FRONTENDURI__NAME=${FRONT_END_NAME}
      - OPENTELEMETRYOPTIONS__SERVICE_NAME=Api.Gateway
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Api.Gateway
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5214
    ports:
      - "5214:5214"
    depends_on:
      - casoft-store-product
      - casoft-store-catalog
      - casoft-store-auth
      - keycloak
      
  casoft-store-auth:
    image: casoftlabs/casoft-store-auth:${TAG}
    container_name: casoft-store-auth
    build:
        context: ../src
        dockerfile: ./Auth.Api/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - KEYCLOAK__CREDENTIALS__SECRET=${KEYCLOAK_CLIENT_SECRET}
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Auth.Api
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - OPENTELEMETRY__JAEGER__AGENTHOST=${OPEN_TELEMETRY_HOST}
      - OPENTELEMETRY__JAEGER__AGENTPORT=6831
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5283
    ports:
      - "5283:5283"
    depends_on:
      - keycloak
    restart: always  
      
  
  casoft-store-basket:
    image: casoftlabs/casoft-store-basket:${TAG}
    container_name: casoft-store-basket
    build:
        context: ../src
        dockerfile: ./Basket.Api/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - KEYCLOAK__CREDENTIALS__SECRET=${KEYCLOAK_CLIENT_SECRET}
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Basket.Api
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - OPENTELEMETRY__JAEGER__AGENTHOST=${OPEN_TELEMETRY_HOST}
      - OPENTELEMETRY__JAEGER__AGENTPORT=6831
      - RABBITMQTRANSPORTOPTIONS__HOST=${RABBITMQ_HOST}
      - RABBITMQTRANSPORTOPTIONS__VHOST=${RABBITMQ_VHOST}
      - RABBITMQTRANSPORTOPTIONS__PORT=${RABBITMQ_PORT}
      - RABBITMQTRANSPORTOPTIONS__USER=${RABBITMQ_USER}
      - RABBITMQTRANSPORTOPTIONS__PASS=${RABBITMQ_PASS}
      - RABBITMQTRANSPORTOPTIONS__PREFIX=${RABBITMQ_PREFIX}
      - RABBITMQTRANSPORTOPTIONS__USESSQL=${RABBITMQ_USESSQL}
      - REDIS__CONNECTIONSTRING=${REDIS_CONNECTIONSTRING}
      - REDIS__INSTANCENAME=${REDIS_INSTANCE_NAME}
      - REDIS__PORT=6379
      - DISCOUNTAPI__BASEURL=${DISCOUNT_API_BASEURL}
      - MONGODBSETTINGS__CONNECTIONSTRING=${MONGO_SERVER_URL}
      - MONGODBSETTINGS__DATABASENAME=${MONGO_DATABASE_NAME}
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5289
    ports:
      - "5289:5289"
    depends_on:
      - rabbitmq
      - keycloak
    restart: always  


  
  casoft-store-billing:
    image: casoftlabs/casoft-store-billing:${TAG}
    container_name: casoft-store-billing
    build:
        context: ../src
        dockerfile: ./Billing.Api/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Billing.Api
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - RABBITMQTRANSPORTOPTIONS__HOST=${RABBITMQ_HOST}
      - RABBITMQTRANSPORTOPTIONS__VHOST=${RABBITMQ_VHOST}
      - RABBITMQTRANSPORTOPTIONS__PORT=${RABBITMQ_PORT}
      - RABBITMQTRANSPORTOPTIONS__USER=${RABBITMQ_USER}
      - RABBITMQTRANSPORTOPTIONS__PASS=${RABBITMQ_PASS}
      - RABBITMQTRANSPORTOPTIONS__PREFIX=${RABBITMQ_PREFIX}
      - RABBITMQTRANSPORTOPTIONS__USESSQL=${RABBITMQ_USESSQL}
      - CONNECTIONSTRINGS__POSTGRESCONNECTION=${BILLING_DB_URL_SERVER}
      - CONNECTIONSTRINGS__DATABASENAME=Payments
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5066
    ports:
      - "5066:5066"
    depends_on:
      - postgres-db
      - rabbitmq
      - keycloak
    restart: always  
      
      
  casoft-store-catalog:
    image: casoftlabs/casoft-store-catalog:${TAG}
    container_name: casoft-store-catalog
    build:
        context: ../src
        dockerfile: ./Api.Catalogo/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - KEYCLOAK__CREDENTIALS__SECRET=${KEYCLOAK_CLIENT_SECRET}
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Api.Catalogo
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5294
    ports:
      - "5294:5294"
    depends_on:
      - mongodb
      - keycloak
    restart: always  
      
  casoft-store-discount:
    image: casoftlabs/casoft-store-discount:${TAG}
    container_name: casoft-store-discount
    build:
        context: ../src
        dockerfile: ./Discount.Api/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - KEYCLOAK__CREDENTIALS__SECRET=${KEYCLOAK_CLIENT_SECRET}
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Discount.Api
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - CONNECTIONSTRINGS__POSTGRESCONNECTION=${DISCOUNT_DB_URL_SERVER}
      - CONNECTIONSTRINGS__DATABASENAME=Coupons
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5025
    ports:
      - "5025:5025"
    depends_on:
      - postgres-db
      - rabbitmq
      - keycloak
    restart: always  
  
  casoft-store-order:
    image: casoftlabs/casoft-store-order:${TAG}
    container_name: casoft-store-order
    build:
        context: ../src
        dockerfile: ./Order.Api/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - KEYCLOAK__CREDENTIALS__SECRET=${KEYCLOAK_CLIENT_SECRET}
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Order.Api
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - RABBITMQTRANSPORTOPTIONS__HOST=${RABBITMQ_HOST}
      - RABBITMQTRANSPORTOPTIONS__VHOST=${RABBITMQ_VHOST}
      - RABBITMQTRANSPORTOPTIONS__PORT=${RABBITMQ_PORT}
      - RABBITMQTRANSPORTOPTIONS__USER=${RABBITMQ_USER}
      - RABBITMQTRANSPORTOPTIONS__PASS=${RABBITMQ_PASS}
      - RABBITMQTRANSPORTOPTIONS__PREFIX=${RABBITMQ_PREFIX}
      - RABBITMQTRANSPORTOPTIONS__USESSQL=${RABBITMQ_USESSQL}
      - CONNECTIONSTRINGS__POSTGRESCONNECTION=${ORDER_DB_URL_SERVER}
      - CONNECTIONSTRINGS__DATABASENAME=Orders
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5121
    ports:
      - "5121:5121"
    depends_on:
      - postgres-db
      - rabbitmq
      - keycloak
    restart: always  

      
  casoft-store-product:
    image: casoftlabs/casoft-store-product:${TAG}
    container_name: casoft-store-product
    build:
        context: ../src
        dockerfile: ./Api.Produto/Dockerfile
    environment:
      - KEYCLOAK__REALM=${KEYCLOAK_REALM}
      - KEYCLOAK__AUTH_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK__SSL_REQUIRED=${KEYCLOAK_SSL_REQUIRED}
      - KEYCLOAK__RESOURCE=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK__VERIFY_TOKEN_AUDIENCE=true
      - KEYCLOAK__CREDENTIALS__SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK__METADATADDRESS=${KEYCLOAK_METADATA_ADRESS}
      - OPENTELEMETRYOPTIONS__ENVIRONMENT= ${OPENTELEMETRY_ENVIROMENT}
      - OPENTELEMETRYOPTIONS__APPNAME=Product.Api
      - OPENTELEMETRYOPTIONS__OTLEXPORTER__ENDPOINT=${OTLEXPORTER_ENDPOINT}
      - OPENTELEMETRYOPTIONS__GRAFANALOKI__ENDPOINT=${GRAFANALOKI_ENDPOINT}
      - RABBITMQTRANSPORTOPTIONS__HOST=${RABBITMQ_HOST}
      - RABBITMQTRANSPORTOPTIONS__VHOST=${RABBITMQ_VHOST}
      - RABBITMQTRANSPORTOPTIONS__PORT=${RABBITMQ_PORT}
      - RABBITMQTRANSPORTOPTIONS__USER=${RABBITMQ_USER}
      - RABBITMQTRANSPORTOPTIONS__PASS=${RABBITMQ_PASS}
      - RABBITMQTRANSPORTOPTIONS__PREFIX=${RABBITMQ_PREFIX}
      - RABBITMQTRANSPORTOPTIONS__USESSQL=${RABBITMQ_USESSQL}
      - BLOBCONTAINERS__CONNECTIONSTRINGS=${AZURE_BLOB_URL}
      - BLOBCONTAINERS__CONTAINERNAME=${BLOB_CONTAINER_NAME}
      - CONNECTIONSTRINGS__POSTGRESCONNECTION=${PRODUCT_DB_URL_SERVER}
      - CONNECTIONSTRINGS__DATABASENAME=Products
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ASPNETCORE_URLS=http://*:5256
    ports:
      - "5256:5256"
    depends_on:
      - postgres-db
      - rabbitmq
      - keycloak
    restart: always  
