services:

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always


  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - postgresql_vol:/var/lib/postgresql/data
        #- ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always        

  mongodb:
    image: mongo:8.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
       MONGO_INITDB_DATABASE: admin
       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    restart: always  
    volumes:
      - mongo_vol:/data/db
      
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite-blob --blobHost 0.0.0.0 --location /data
    restart: always
    ports:
      - "10000:10000" # Blob
      # - "10001:10001" # Queue
      # - "10002:10002" # Table
    volumes:
      - azurite_data:/data    