route:
  receiver: 'Default'
  group_by: ['alertname', 'team', 'instance']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  routes:

    - receiver: AlertGatewayApi
      group_wait: 10s
      match:
        team: "casoft-api-gateway"
      continue: true    

    - receiver: AlertApiAuth
      group_wait: 10s
      match:
        team: "casoft-api-auth"
      continue: true 

    - receiver: AlertBasketApi
      group_wait: 10s
      match:
        team: "casoft-store-basket"
      continue: true    

    - receiver: AlertBillingApi
      group_wait: 10s
      match:
        team: "casoft-store-billing"
      continue: true 

    - receiver: AlertCatalogApi
      group_wait: 10s
      match:
        team: "casoft-store-catalog"
      continue: true 

    - receiver: AlertDiscountApi
      group_wait: 10s
      match:
        team: "casoft-discount-api"
      continue: true 

    - receiver: AlertOrderApi
      group_wait: 10s
      match:
        team: "casoft-order-api"
      continue: true     

    - receiver: AlertProductApi
      group_wait: 10s
      match:
        team: "casoft-store-product"
      continue: true

    - receiver: AlertProductApi2
      group_wait: 10s
      match:
        team: "casoft-store-product"
      continue: true

    - receiver: AlertProductApi3
      group_wait: 10s
      match:
        team: "casoft-store-product"
      continue: true

    # Rota padrão (fallback)
    - receiver: Default
      match:
        team: ""  # Captura alertas SEM a label 'team'
      continue: false

receivers:
  - name: Default
    webhook_configs:
      - url: 'http://alertview:8181/webhook'

  - name: AlertGatewayApi
    webhook_configs:
      - url: 'http://alertview:8181/webhook'

  - name: AlertApiAuth
    webhook_configs:
      - url: 'http://alertview:8181/webhook'  
      
  - name: AlertBasketApi
    webhook_configs:
      - url: 'http://alertview:8181/webhook'      

  - name: AlertBillingApi
    webhook_configs:
      - url: 'http://alertview:8181/webhook'

  - name: AlertCatalogApi
    webhook_configs:
      - url: 'http://alertview:8181/webhook'

  - name: AlertDiscountApi
    webhook_configs:
      - url: 'http://alertview:8181/webhook'

  - name: AlertOrderApi
    webhook_configs:
      - url: 'http://alertview:8181/webhook'

  - name: AlertProductApi
    webhook_configs:
      - send_resolved: true
        url: 'http://alertview:8181/webhook' 

  - name: 'AlertProductApi2'
    webhook_configs:
      - send_resolved: true
        url: 'http://promteams:2000/high_priority_channel'

  - name: 'AlertProductApi3'
    webhook_configs:
      - send_resolved: true
        url: 'http://promteams:2000/low_priority_channel'                                                     