groups:
- name: GatewayApi
  rules:
  - alert: GatewayApiAlert
    expr: rate(mongodb_op_counters_total{type="query"}[10m]) > 0.15
    for:  5s
    labels:
      team: casoft-api-gateway
    annotations:
      summary: "Muitas consultas"
      description: "O {{ $labels.instance }} Gateway API received to many requests ({{ $value }})"

 # Este alerta monitora a taxa de requisições recebidas pela API "Product.Api" em cada instância.
 # Se qualquer instância receber, em média, mais de 10 requisições por segundo durante pelo menos 30 segundos, o alerta será disparado.
 # Isso pode indicar uma sobrecarga, ataque ou aumento inesperado de uso, e o Alertmanager pode notificar a equipe responsável com as informações configuradas
- name: ProductAPI
  rules:
  - alert: ProductApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Product.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-store-product # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Product API received to many requests ({{ $value }}). [Click here to check](http://seusistema.com/dashboard?instance={{ $labels.instance }})"
      runbook_url: "http://seusistema.com/docs"

- name: BasketAPI
  rules:
  - alert: BasketApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Basket.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-store-basket # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Basket API received to many requests ({{ $value }})"      

- name: BillingAPI
  rules:
  - alert: BillingApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Billing.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-store-billing # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Billing API received to many requests ({{ $value }})"

- name: CatalogAPI
  rules:
  - alert: CatalogApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Catalog.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-store-catalog # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Catalog API received to many requests ({{ $value }})"

- name: DiscountAPI
  rules:
  - alert: DiscountApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Discount.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-discount-api # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Discount API received to many requests ({{ $value }})"

- name: OrderAPI
  rules:
  - alert: OrderApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Order.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-order-api # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Order API received to many requests ({{ $value }})"

- name: AuthAPI
  rules:
  - alert: AuthApiAlert - To many requests
    expr: sum(rate(http_server_request_duration_seconds_count{appName="Auth.Api"}[1m])) by (instance) > 10
    for: 30s # O alerta só será disparado se a condição acima se mantiver verdadeira por pelo menos 30
    labels:
      team: casoft-api-auth # serve para o alertmanager rotear o alerta, usado no arquivo alertmanager.yml
    annotations:
      summary: "High number of requests"
      description: "{{ $labels.instance }} Auth API received to many requests ({{ $value }})"                              