auth_enabled: false # Desativa autenticação no Loki. Qualquer um pode acessar as APIs e endpoints do Loki sem precisar de autenticação.

server:
  http_listen_port: 3100
  http_server_read_timeout: 20m # Tempo máximo que o servidor vai esperar para ler uma requisição (20 minutos).
  http_server_write_timeout: 20m # Tempo máximo que o servidor vai esperar para escrever uma resposta (20 minutos).
  grpc_server_max_recv_msg_size: 104857600 # Tamanho máximo de mensagem recebida via gRPC (100 MB).
  grpc_server_max_send_msg_size: 104857600 # Tamanho máximo de mensagem enviada via gRPC (100 MB).
#  cors:
#    allowed_origins: ["*"]  # You can replace "*" with the specific domains you want to allow
#    allowed_methods: ["GET", "POST", "OPTIONS", "DELETE", "PUT"]
#    allowed_headers: ["Content-Type", "Authorization"]
#    exposed_headers: []
#    allow_credentials: false

common:
  path_prefix: /loki # Define o prefixo de caminho onde os dados e arquivos do Loki serão armazenados.
  storage:
    filesystem:
      chunks_directory: /loki/chunks # Onde os arquivos de chunks (blocos de logs) serão salvos no disco.
      rules_directory: /loki/rules # Onde as regras de alertas do Loki serão salvas.
  replication_factor: 1 # Define o fator de replicação dos dados. Com valor 1, não há replicação (apenas uma cópia dos dados).
  ring:
    kvstore:
      store: inmemory # O anel de distribuição de dados (ring) usa armazenamento em memória para manter o estado. Isso é comum em ambientes de teste ou instâncias únicas (não recomendado para produção com alta disponibilidade).

schema_config:
  configs:
    - from: 2020-10-24 # A partir dessa data, esta configuração de schema entra em vigor.
      store: boltdb-shipper # O Loki usa o boltdb-shipper para armazenar índices localmente e sincronizá-los com o armazenamento de objetos.
      object_store: filesystem # O armazenamento de objetos dos logs será no próprio sistema de arquivos, não em nuvem.
      schema: v11 # Versão do schema usado para organizar os dados.
      index:
        prefix: index_ # Prefixo dos arquivos de índice.
        period: 24h # Cria um novo índice a cada 24 horas.

ruler:
  alertmanager_url: http://localhost:9093 # Endereço do Alertmanager para onde o Loki enviará alertas configurados nas regras.

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false
limits_config:
  # Maximum number of log entries that will be returned for a query. default = 5000
  max_entries_limit_per_query: 200000