global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
        - 'localhost:9090'

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'casoft-product-api'
    scheme: https
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'casoft-product-api:7213'
        labels:
          team: casoft-product-api
    tls_config:
      insecure_skip_verify: true

# adicionar os demais jobs de scrape aqui

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets: 
          - 'alertmanager:9093'