
name : Executing Tests
on:
    workflow_call:

jobs:

  unit-tests:
    name: Quality Gate ⚙️
    runs-on: ubuntu-latest
    concurrency:
          group: example-group
          cancel-in-progress: true  
    steps:
      - name: Getting project code ⏳
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.300   

      - name: Installing dotnet-coverage ⏳
        run: dotnet tool install --global dotnet-coverage

      - name: Installing SonarQube ⏳
        run: dotnet tool install --global dotnet-sonarscanner   

      - name: Build and Analysis  🛠️
        run: |
          dotnet sonarscanner begin /o:"cesaragsuc" /k:"CesaragsUC_master-project" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --configuration Release
          dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      
      - name: Analysing Quality Gate 👀🐞🧐
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        with:
          scanMetadataReportFile: ./.sonarqube/out/.sonar/report-task.txt

      - name: "SonarQube Quality Gate Status:"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
