global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
        - 'https://prometheus.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['https://otel-collector.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io']

  - job_name: 'casoft-store-api-gateway'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-api-gateway.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-api-gateway


  - job_name: 'casoft-store-auth'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-auth.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-auth


  - job_name: 'casoft-store-basket'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-basket.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-basket

  - job_name: 'casoft-store-billing'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-billing.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-billing


  - job_name: 'casoft-store-catalog'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-catalog.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-catalog

  - job_name: 'casoft-store-discount'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-discount.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-discount

  - job_name: 'casoft-store-order'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-order.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-order

  - job_name: 'casoft-store-product'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: 
         - 'https://casoft-store-product.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'
        labels:
          team: casoft-store-product


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets: 
          - 'https://alertmanager.thankfulmushroom-fe2ec090.eastus2.azurecontainerapps.io'