name : Deploy on ACA
on:
    workflow_call:
          inputs:
            version:
                required: true
                type: string
                description: 'version of the app to deploy'
env:
    RESOURCE_GROUP: casoft
    DOCKER_NAMESPACE: casoftlabs
    # Container Apps
    # Ned to create a container app in Azure with exactly the same name.
    CATALOG_CONTAINER_APP: casoft-store-catalog
    GATEWAY_CONTAINER_APP: casoft-store-api-gateway
    AUTH_CONTAINER_APP: casoft-store-auth
    BASKET_CONTAINER_APP: casoft-store-basket
    BILLING_CONTAINER_APP: casoft-store-billing
    DISCOUNT_CONTAINER_APP: casoft-store-discount
    ORDER_CONTAINER_APP: casoft-store-order
    PRODUCT_CONTAINER_APP: casoft-store-product   

jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     concurrency:
          group: example-group
          cancel-in-progress: true  
     # This job will only run on the main branch
     if: github.ref == 'refs/heads/main'
     environment:
        name: production
     steps:

      - name: New version recived
        run: |
          echo "New version is ${{ inputs.version }}"
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App CATALOG
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CATALOG_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CATALOG_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production


      - name: Deploy to Azure Container App GATEWAY
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.GATEWAY_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.GATEWAY_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container App AUTH
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.AUTH_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.AUTH_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container App BASKET
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.BASKET_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.BASKET_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container App BILLING
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.BILLING_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.BILLING_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container App DISCOUNT  
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.DISCOUNT_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.DISCOUNT_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container App ORDER
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.ORDER_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.ORDER_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container App PRODUCT
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PRODUCT_CONTAINER_APP }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.PRODUCT_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production
