name : Deploy on ACA
on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
                description: 'Version of the image to deploy'
env:
    RESOURCE_GROUP: casoft

    # Container Apps
    # Ned to create a container app in Azure with exactly the same name.
    CATALOG_CONTAINER_APP: casoft-store-catalog
    GATEWAY_CONTAINER_APP: casoft-store-api-gateway
    AUTH_CONTAINER_APP: casoft-store-auth
    BASKET_CONTAINER_APP: casoft-store-basket
    BILLING_CONTAINER_APP: casoft-store-billing
    DISCOUNT_CONTAINER_APP: casoft-store-discount
    ORDER_CONTAINER_APP: casoft-store-order
    PRODUCT_CONTAINER_APP: casoft-store-product   

jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
      - name: Version received
        run: |
            echo "Version received is: ${{ inputs.version }}"
