name : Deploy on ACA
on:
    workflow_call:
          inputs:
            version:
                required: true
                type: string
                description: 'version of the app to deploy'
env:
    RESOURCE_GROUP: casoft
    DOCKER_NAMESPACE: casoftlabs
    # Container Apps
    # Ned to create a container app in Azure with exactly the same name.
    CATALOG_CONTAINER_APP: casoft-store-catalog
    GATEWAY_CONTAINER_APP: casoft-store-api-gateway
    AUTH_CONTAINER_APP: casoft-store-auth
    BASKET_CONTAINER_APP: casoft-store-basket
    BILLING_CONTAINER_APP: casoft-store-billing
    DISCOUNT_CONTAINER_APP: casoft-store-discount
    ORDER_CONTAINER_APP: casoft-store-order
    PRODUCT_CONTAINER_APP: casoft-store-product   

jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
      - name: New version recived
        run: echo "New version is ${{ inputs.version }}"
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container CATALOG
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_CATALOG }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CATALOG_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container GATEWAY
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_API_GATEWAY }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.GATEWAY_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container AUTH
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_AUTH }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.AUTH_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container BASKET
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_BASKET }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.BASKET_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container BILLING
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_BILLING }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.BILLING_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container DISCOUNT
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_DISCOUNT }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.DISCOUNT_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container ORDER
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_ORDER }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.ORDER_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production

      - name: Deploy to Azure Container PRODUCT
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_NAMESPACE }}/${{ vars.CONTAINER_APP_PRODUCT }}:${{ inputs.version }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.PRODUCT_CONTAINER_APP }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production
